### ISSUE TITLE
Switch selector

### ISSUE THREAD

**Issue by nitrocs** [MFornander/Hubitat#1]
It would be helpful to be able to select switches PER child -- I dont need all notifications to go to every switch.

@dan3 on HE forum

**Comment by SebastienViel** [comment]
I second that.  Also, some notification types for Inovelli (Ex.: Chase) only work on some switch types and not on others.  It would be good to be able to specify the notification type per switch type.

**Comment by MFornander** [comment]
Not quite sure I understand.  Would you like some notifications to show up on some switches and other notifications on others?  If so, I think you can do this by creating a second parent app that represents a different dashboard instance that can show completely different conditions on a different set of switches.  Does that work?

**Comment by SebastienViel** [comment]
Creating different instances of the app would work for me.  Here are 2 use cases:

1. I want a notification indicating my air exchanger is on Turbo, but only on a specific switch in each bathroom and kitchen.  I want the open garage door to display on most switches, but not those mentioned previously.
2. Some effects are only available on the dimmer, so I need to have the ability to send two distinct commands to dimmers vs switches.

More than one parent would work for both those use cases.  Another option would be to put the device selection on the child, or have the ability to pick the devices to use in the child...  that second option would be cleaner (keeps everything together and linked to the main app), but would be a lot more work I suspect...

**Comment by MFornander** [comment]
Yeah it's a good idea but it would change a lot in the design and I'm itching to implement my AI bear detector (true story) instead of refactor this.  Have to use the multi-parent I'm afraid :|
