### ISSUE TITLE
Switch to disable the auto-off

### ISSUE THREAD

**Issue by xdreamwalker** [MFornander/Hubitat#11]
Feature Request
Use a virtual switch to disable the auto-off. Ideally, once this virtual switch is off, then the auto-off timer would start back up keeping track of the times for each light.

**Comment by OzzBoz** [comment]
Request. Add an option to turn on switch instead of off.  Case use: We ask google to sometimes turn off automations and need these to turn back after a set time.

**Comment by MFornander** [comment]
Added in v1.1 pushed just now
