### ISSUE TITLE
Add valves to the sensor list

### ISSUE THREAD

**Issue by zarthan** [MFornander/Hubitat#15]
Water and gas valves would be great devices to monitor with the LED indicator lights. I do not know whether an irrigation system would show up as a valve but if so, I can imagine having some easily visible indicator that the water is on would be helpful. In my case, I have a gas valve that supports outdoor gas appliances.

**Comment by MFornander** [comment]
Done!  I hope :) Let me know how it works since I can't test it without any valve devices here.

**Comment by zarthan** [comment]
It complains 
Required Fields missing or not passing validation. Please check red underlined fields and complete the required fields (ones with *)

**Comment by zarthan** [comment]
It works. Thanks
