### ISSUE TITLE
import Url needs to be on line 1 in order to work with apps

### ISSUE THREAD

**Issue by SebastienViel** [MFornander/Hubitat#3]
Not sure if this is an issue anymore...  importUrl didn't work for me on version 1.0.0.  It works now on version 1.1.0, so this may not be an issue...

Some apps have the following on line 1:
`// IMPORT URL: https://raw.githubusercontent.com/MFornander/Hubitat/master/apps/SwitchDashboard/SwitchDashboard-parent.groovy`

**Comment by MFornander** [comment]
Added to v1.2, just committed. Not sure what is going on here but added that line to test it out.

**Comment by MFornander** [comment]
FYI, top line didn't work.  Reading on forum and testing,  it seems like only drivers pick up the importUrl field.  So with apps I recommend doing an import from the start instead of pasting in the full code.  Thar way the import dialog remembers the URL you pasted in.
