### ISSUE TITLE
Bug - Some Inovelli drivers not supported

### ISSUE THREAD

**Issue by SebastienViel** [MFornander/Hubitat#4]
Older as well as the Hubitat version of the Inovelli drivers are not supported.

Recommending that a pop-up state that there is an issue with the driver and recommend updating.  Documentation could also be updated to recommend a specific version.

**Comment by MFornander** [comment]
Good idea.  Have some ideas how to verify the device driver used.  Look for it in the next v1.3

**Comment by SebastienViel** [comment]
Cool!

**Comment by MFornander** [comment]
Added a nice UI error for unsupported devices and much better logging in the new v1.3
