### ISSUE TITLE
Enhancement - Link to Inovelli Toolbox directly in settings

### ISSUE THREAD

**Issue by SebastienViel** [MFornander/Hubitat#5]
Currently, the user may need to navigate back to the instructions, or may not realize that they need to pull-up the Inovelli toolbox to get the Inovelli Configuration Value.

Recommending that the link be added directly in the configuration page.  Also recommending that the description indicate that it provides support for the LED effects.

**Comment by MFornander** [comment]
Added to v1.2, just committed.
