### ISSUE TITLE
Separate Configuration Value for dimmers vs switches

### ISSUE THREAD

**Issue by SebastienViel** [MFornander/Hubitat#6]
Because I want some alerts to use the chase effect on my dimmers, I need to have 2 instances of the app installed.

Would it be possible to allow the children app to distinguish between the Inovelli switchs and dimmers, like it does between Inovelli and Homeseer device types, so that one child app could control both in this type of situation?

There could be an additional optional field that would be for dimmer configuration value which would be picked up by the dimmer only (when filled). When empty, the current field would be used. (Most codes are the same for both.)

Thanks!

**Comment by MFornander** [comment]
This would be so much easier if Inovelli had a sane effect index on their API. Could you chime in below and ask for them to unify their effect indices between devices?
https://community.inovelli.com/t/feedback-after-using-the-driver-api-on-gen2-devices/3240

**Comment by SebastienViel** [comment]
I totally agree...  but what do you think the chances are of them changing this now...?  I added my agreement to their community.

**Comment by MFornander** [comment]
It will probably be a month or more but I'm hoping they start over at, say 10 and deprecate the old values.  I'm probably going to replicate their full range with a Hubitat UI (effect, hue, brightness) the next week and do the switch/dimmer logic. What should the fallback for Chase be on the switch?

**Comment by SebastienViel** [comment]
It will be nice if they can fix that. Odd that they didn’t think about that...

I would recommend that Pulse be the fallback for chase. It is the effect that most resembles it.

You’ll have to tell me more about that Bear AI!  You peaked my curiosity!

**Comment by MFornander** [comment]
Fixed in v1.5.  The app now translate dimmer notification values automatically to switches.

Regarding the bear: we have bears raiding our trash there in Colorado.  Planning to make a bear detector so if my alley camera sees a bear, it does something to scare it off.  Like face detector but with bears.  or mountain lions, or raccoons :)

**Comment by SebastienViel** [comment]
Wow!  That sounds like quite the project!
