### ISSUE TITLE
Priority not working between apps

### ISSUE THREAD

**Issue by SebastienViel** [MFornander/Hubitat#7]
When there are multiple instances of the app installed, the priority does not work. The last notification to turn on or off takes priority over the previous one.

**Comment by MFornander** [comment]
Yeah unfortunately a switch can only belong to one dashboard since there it no easy way for various dashboards to share states.

**Comment by MFornander** [comment]
Not going to fix this unfortunately since app-to-app communication is outside my Hubitat energy right now.
